AWSTemplateFormatVersion: '2010-09-09'
Description: S3 replication + CloudTrail logging for object-level activities
Resources:
  CloudTrailLogBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: cloudtrail-logs-618480996782
      AccessControl: LogDeliveryWrite
      VersioningConfiguration:
        Status: Enabled
  S3ReplicationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: S3ReplicationRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3ReplicationPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetReplicationConfiguration
                  - s3:ListBucket
                Resource: arn:aws:s3:::polystudents3-618480996782
              - Effect: Allow
                Action:
                  - s3:GetObjectVersion
                  - s3:GetObjectVersionAcl
                  - s3:GetObjectVersionForReplication
                  - s3:GetObjectVersionTagging
                Resource: arn:aws:s3:::polystudents3-618480996782/*
              - Effect: Allow
                Action:
                  - s3:ReplicateObject
                  - s3:ReplicateDelete
                  - s3:ReplicateTags
                Resource: arn:aws:s3:::polystudents3-back/*
  PolyStudentS3:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: polystudents3-618480996782
      VersioningConfiguration:
        Status: Enabled
      ReplicationConfiguration:
        Role: !GetAtt S3ReplicationRole.Arn
        Rules:
          - Id: ReplicateAllToBackup
            Status: Enabled
            Prefix: ""
            Destination:
              Bucket: arn:aws:s3:::polystudents3-back
  S3ActivityTrail:
    Type: AWS::CloudTrail::Trail
    Properties:
      TrailName: S3ObjectActivityTrail
      S3BucketName: !Ref CloudTrailLogBucket
      IsLogging: true
      IsMultiRegionTrail: true
      IncludeGlobalServiceEvents: true
      EventSelectors:
        - ReadWriteType: All
          IncludeManagementEvents: false
          DataResources:
            - Type: AWS::S3::Object
              Values:
                - arn:aws:s3:::polystudents3-618480996782/